services:
  db:
    image: "mysql:8.4.3"
    environment:
      MYSQL_DATABASE: 'biblioteca'
      MYSQL_ROOT_PASSWORD: "123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./db/script.sql:/docker-entrypoint-initdb.d/init.sql"

  node:
      depends_on:
        - db
      image: "node:22"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ./:/home/node/app
      ports: # use if it is necessary to expose the container to the host machine
        - "3000:3000"
      command: ["npm", "start"]      
volumes:
  my-db: